version: "3.8"
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: mvc-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: mvc-app-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  # mysql:
  #   container_name: mvc-app-db
  #   image: mysql:8.0
  #   volumes:
  #     - ./storage/mysql:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root

  db:
    container_name: mvc-app-db
    image: postgres:13
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
